@startuml
actor User

participant "Controllers" as Input
participant "On-Screen Notifications" as HUD
participant "Unity Vivox SDK" as CCM
participant "Network Services" as NM


== Voice Chat ==

User -> NM : Authenticate and join session
NM --> CCM : Voice access granted
CCM -> NM : Join Voice channel
CCM -> HUD : Show "Connected to Voice" message

loop While moving
    User -> Input : Move or turn head
    Input -> CCM : Send new head position
    CCM -> NM : Update voice location
end

alt Muting self
    User -> HUD : Press Mute in Menu
    HUD -> CCM : Turn off microphone
    CCM -> NM : Tell network to stop sending audio
    CCM -> HUD : Show "Mic: OFF"

end

== Public Text Chat ==

User -> HUD : Type message in the UI chat box
HUD -> CCM : Submit message locally
CCM -> NM : Send message to server
NM -> NM : Add to master message list
NM --> CCM : Broadcast to all other users
CCM -> HUD : Display message on everyone's screen
@enduml
