
@startuml
actor User
participant "Input Manager" as Input
participant "HUD Manager" as HUD
participant "Room Manager" as Room
participant "Auth Manager" as SM
/'participant "Event Logger" as Logger'/

title Create an art room

== Basic Flow ==

User -> Input: clicks on HUD icon
/'Input -> Logger: log user event'/
Input -> HUD: requests HUD
User -> Input: clicks on create new room
/'Input -> Logger: log user event'/
Input -> HUD: validates and sends event information to HUD 
/'Input -> Logger: log user event'/
HUD -> User: modal with options (room name, privacy type) is opened
User -> Input: Enters room's name and privacy type (public or private)
/'Input -> Logger: log user event'/
Input -> HUD: validates and sends event information to HUD
HUD -> Room: requests a room with user information
 
== Alternative Flow 1 – Private Room ==

Room -> SM: creates a room and requests a security layer.
SM -> Room: encrypts the room to make it private
Room -> User: notifies creation of private room.


== Alternative Flow 2 – Public Room ==

Room -> User: notifies creation of public room

@enduml
